# -*- coding: utf-8 -*-
"""exercicio-01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ktcIihEwUEfLMbPB2q5vpt_1GEZawTu8
"""

type(1) #o resultado mostrará que o tipo do dado é um número inteiro.

type(True) #resultado correspondente ao tipo de valor lógico verdadeiro.

type(5/2) #resultado correspondente ao tipo de número real ou flutuante.

type(2.5) #resultado do tipo float correspondente à número real ou flutuante.

type(False) #resultado correspondente ao tipo de valor lógico verdadeiro.

type(5+3j) #tipo de dado de número complexo.