# -*- coding: utf-8 -*-
"""exercicio-02

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HBneEZla4DN75GHOW8_ehNVoXuogUKrQ
"""

x=5/2 
type(x)
print("resultado da operação:",(x),'\n', 'tipo do dado:', type(x))

y=7 * 4 + 2
type(y)
print("resultado da expressão:",(y),'\n', 'tipo do dado:', type(y))

w=(7 * 4) + 2
type(w)
print("resultado da operação:",(w),'\n', 'tipo do dado:', type(w))

r=7 * (4 + 2)
type(r)
print("resultado da operação:",(r),'\n', 'tipo do dado:', type(r))

f=2 ** 3 # ** valor de exponencial#
type(f)
print("resultado da operação:",(f),'\n', 'tipo do dado:', type(f))

a=2 ** 3 ** 4
type(a)
print("resultado da operação:",(a),'\n', 'tipo do dado:', type(a))

b=2 ** -3 ** 4
type(b)
print("resultado da operação:",(b),'\n', 'tipo do dado:', type(b))

c=5 % 2  #% representa o resto da divisão#
type(c)
print("resultado da operação:",(c),'\n', 'tipo do dado:', type(c))

z=6 % 2
type(z)
print("resultado da operação:",(z),'\n', 'tipo do dado:', type(z))

e=7 % 2
type(e)
print("resultado da operação:",(e),'\n', 'tipo do dado:', type(e))

h=8 % 2
type(h)
print("resultado da operação:",(h),'\n', 'tipo do dado:', type(h))

k=5 + 1
type(k)
print("resultado da operação:",(k),'\n', 'tipo do dado:', type(k))

m=5.0 + 1
type(m)
print("resultado da operação:",(m),'\n', 'tipo do dado:', type(m))

import math #importação da biblioteca para operações matemáticas mais avançadas

p=5 * math.log10(100) - 8 ** 2 #valores de logaritimo
type(p)
print("resultado da operação:",(p),'\n', 'tipo do dado:', type(p))

v=math.pi #valor de pi
type(v)
print("resultado da operação:",(v),'\n', 'tipo do dado:', type(v))

t=math.sin(math.pi / 2 ) #valores de seno.
type(t)
print("resultado da operação:",(t),'\n', 'tipo do dado:', type(t))

s=math.cos(math.pi / 4 ) #valores de cosseno.
type(s)
print("resultado da operação:",(s),'\n', 'tipo do dado:', type(s))