# -*- coding: utf-8 -*-
"""exercicio-03

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E1PkBiPigDX_X4JDRWsnRr-OFElJlivA

NDWI
"""

Xgreen= 555
Xnir= 858

NDWI = (Xnir - Xgreen)/(Xnir + Xgreen)
print(NDWI)

"""NDVI"""

Xred= 645 
Xnir= 858

NDVI = (Xnir - Xred)/(Xnir + Xred)
print(NDVI)